config/routes.rb
CS2102::Application.routes.draw do

  root :to => 'home#index', :as => :home
  
  resources :bookings

  resources :customers

  resources :packages

  resources :services
  resources :rooms

  resources :hotels

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  has_many :services, dependent: :destroy
  has_many :rooms, dependent: :destroy, :foreign_key => :hotel_id
  
  #attr_accessible :name, :stars, :city, :country, :address, :phone
  
  validates :name, :stars, :city, :country, :address, :phone, presence: true
  validates :stars, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 5}  
  # Primary key 
  validates :name, :uniqueness => {:scope => :city}
  
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render action: 'show', status: :created, location: @hotel }
      else
        format.html { render action: 'new' }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:name, :stars, :city, :country, :address, :phone, :descrpition)
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_for(@hotel) do |f| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% @hotel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :stars %><br>
    <%= f.number_field :stars %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :descrpition %><br>
    <%= f.text_area :descrpition %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<h1>Listing hotels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Stars</th>
      <th>City</th>
      <th>Country</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Descrpition</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.name %></td>
        <td><%= hotel.stars %></td>
        <td><%= hotel.city %></td>
        <td><%= hotel.country %></td>
        <td><%= hotel.address %></td>
        <td><%= hotel.phone %></td>
        <td><%= hotel.descrpition %></td>
        <td><%= link_to 'Show rooms', hotel %></td>
        <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
        <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hotel', new_hotel_path %>

app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render 'form' %>

<%= link_to 'Back', hotels_path %>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hotel.name %>
</p>

<p>
  <strong>Stars:</strong>
  <%= @hotel.stars %>
</p>

<p>
  <strong>City:</strong>
  <%= @hotel.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @hotel.country %>
</p>

<p>
  <strong>Address:</strong>
  <%= @hotel.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @hotel.phone %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hotel.descrpition %>
</p>


<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>